theme: jekyll-theme-midnight
collections:
  bots:
    output: true
    permalink: /:path
    sort_by: botRarityNumber
  abilities:
    output: true
    permalink: /:path
  boosters:
    output: true
    permalink: /:path
  gadgets:
    output: true
    permalink: /:path
    
title: Botworld Wiki
description: Robopedia, Guides & Tips collected by the community
logo: https://cdn.discordapp.com/emojis/918669937214640269.png

plugins:
  - jekyll-sitemap
