theme: jekyll-theme-midnight
collections:
  bots:
    output: true
    permalink: /:path
  abilities:
    output: true
    permalink: /:path
  boosters:
    output: true
    permalink: /:path
  materials:
    output: true
    permalink: /:path
    
title: Botworld Wiki
description: Robopedia, Guides & Tips collected by the Community
logo: https://www.botworld.wiki/assets/img/icons/cog.png

plugins:
  - jekyll-sitemap
